# Created 2-21 on K8s 1.20

# A cronjob that runs once a day

# Docs: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: apache-cronjob
  namespace: apache
  annotations:
spec:
  schedule: "* * */1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: apache-cronjob
            image: httpd:2.4.46
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - date; echo I am an example cronjob; sleep 30
            resources:
              requests:
                cpu: 0.1
                ephemeral-storage: 0.5Gi
                memory: 0.1G
              limits:
                cpu: 0.2
                memory: 0.2G
                ephemeral-storage: 2Gi
          restartPolicy: OnFailure

