# Create 2-21 on K8s 1.20
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
# Cluster managers, hosting providers, etc should use tools which respect Pod Disruption Budgets路
#   by calling the Eviction API instead of directly deleting pods, for voluntary actions.
# Involuntary actions also count against the budget.路
# The kubectl drain command utilizes pod disruption budgets
# Pods which are deleted or unavailable due to a rolling upgrade to an application do count路
#   against the disruption budget, but controllers (like deployment and stateful-set) are not路
#   limited by PDBs when doing rolling upgrade.
metadata:
  name: apache-pdb
  namespace: apache
  annotations:
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: apache
