# Created 2-21 on K8s 1.20

# Is a wide open Pod Security Policy

# Documentation: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
# Reference (v1.20): https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#podsecuritypolicy-v1beta1-policy

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: apache-psp-privileged
  # This object type doesn't reside in a namespace # namespace: apache
  annotations:
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'

