# Created 2-21 on K8s 1.20

apiVersion: v1
kind: Secret
metadata:
  name: apache-secret
  namespace: apache
  annotations:
data:
  # Note secrets must always be in base64, I created this via: echo my-example-user-name |base64
  # To test it, take the value and decode it with echo bXktZXhhbXBsZS1wYXNzd29yZAo= |base64 --decode
  password-from-secret: bXktZXhhbXBsZS1wYXNzd29yZAo=
