# Created 2-21 on K8s 1.20

apiVersion: v1
kind: Secret
metadata:
  name: apache-secret
  namespace: apache
  annotations:
data:
  # Note secrets must always be in base64
  password-from-secret: bXktZXhhbXBsZS1wYXNzd29yZAo=
