# Created 2-21 on K8s 1.20
apiVersion: v1
kind: Service
# A service is an abstraction which defines a logical set of Pods and a policy by which to access them.
# For Kubernetes-native applications a simple Endpoints API is updated whenever the set of Pods
#   in a Service changes. For non-native applications, Kubernetes offers a virtual-IP-based bridge
#   to Services which redirects to the backend Pods. Is a layer 4 construct.·

apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
  annotations:
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: apache
